### ISSUE TITLE
DB構成を考える

### ISSUE THREAD

**Issue by Khmer495** [jphacks/F_2002_1#3]
ドキュメントは[こちら](https://github.com/jphacks/F_2002_1/blob/main/database/README.md)

**Comment by Khmer495** [comment]
デザイン側のUI等からとりあえず要りそうなものを定義  
センサー周りを主として追加・変更の余地あり

**Comment by konnyaku256** [comment]
ドキュメントに沿って、Go, GormとMySQL間のマッピングをします
